version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: school-database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: my_api
    depends_on:
      - postgres
    ports:
      - "4444:4444"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/school-database

volumes:
  pgdata:
